version: "3"

networks:
  default:

services:

  seller:
    container_name: seller
    build:
      dockerfile: seller/Dockerfile
      args:
        - PHP_FROM
    volumes:
      # nginx
      - ./seller/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./seller/etc/nginx/http.d:/etc/nginx/http.d
      # supervisor
      - ./seller/etc/supervisord.conf:/etc/supervisord.conf
      - ./seller/etc/supervisor.d:/etc/supervisor.d
      # php
      - ./seller/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./seller/usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d
      # app
      - ./seller/www/s-backend:/app
      # log
      - ./seller/log:/log
      # vendor
      - ./common/yii2-vendor:/data/www/yii2-vendor
      # env
      - ./common/env:/data/web/app
      # geoip
      - ./common/geoip:/data/geoip
    ports:
      - "8201:8201"
    networks:
      default:

  buyer:
    container_name: buyer
    build:
      dockerfile: buyer/Dockerfile
      args:
        - PHP_FROM
    volumes:
      # nginx
      - ./buyer/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./buyer/etc/nginx/http.d:/etc/nginx/http.d
      - ./buyer/etc/nginx/ssl:/etc/nginx/ssl
      # supervisor
      - ./buyer/etc/supervisord.conf:/etc/supervisord.conf
      - ./buyer/etc/supervisor.d:/etc/supervisor.d
      # php
      - ./buyer/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./buyer/usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d
      # app
      - ./buyer/www/buyer:/app
      # log
      - ./buyer/log:/log
      # vendor
      - ./common/yii2-vendor:/data/www/yii2-vendor
      # env
      - ./common/env:/data/web/app
      # geoip
      - ./common/geoip:/data/geoip
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
      
  plugins:
    container_name: plugins
    build:
      dockerfile: plugins/Dockerfile
      args:
        - PHP_FROM
    volumes:
      # nginx
      - ./plugins/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./plugins/etc/nginx/http.d:/etc/nginx/http.d
      # supervisor
      - ./plugins/etc/supervisord.conf:/etc/supervisord.conf
      - ./plugins/etc/supervisor.d:/etc/supervisor.d
      # php
      - ./plugins/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./plugins/usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d
      # app
      - ./plugins/www/plugins:/app
      # vendor
      - ./common/yii2-vendor:/data/www/yii2-vendor
      # env
      - ./common/env:/data/web/app
      # geoip
      - ./common/geoip:/data/geoip
    ports:
      - "8202:8202"
    networks:
      default:

  mysql:                                            #mysql服务节点
    image: mysql:8.0.34                             #mysql镜像，如果镜像容器没有会去自动拉取
    container_name: mysql                           #容器的名称
    command:
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --lower-case-table-names=1                  #忽略数据表明大小写
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      default:

